version: "3.9"

networks:
    playground:
        driver: overlay

secrets:
    PG_JAEGER_BASIC_AUTH:
        external: true

services:
    swarm-hello-world:
        image: lumaghg/swarm-hello-world:20231017.16
        ports:
            - 3000:4000
        environment:
            - port=4000
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
                - "traefik.http.routers.whoami.entrypoints=web"
                - "traefik.http.services.whoami.loadbalancer.server.port=4000"
            replicas: 2
        networks:
            - playground

    traefik:
        image: "traefik:v2.9"
        command:
            - "--log.level=DEBUG"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--providers.docker.swarmMode=true"
            - "--entrypoints.web.address=:80"
            - "--accesslog=true"
            - "--tracing.jaeger=true"
            - "--tracing.jaeger.samplingServerURL=http://jaeger:5778/sampling"
            - "--tracing.jaeger.localAgentHostPort=jaeger:6831"
            - "--tracing.jaeger.propagation=jaeger"
            - "--api.insecure=true"
            - "--providers.docker.network=pg_playground"
        ports:
            - 80:80

        volumes:
            - "//var/run/docker.sock:/var/run/docker.sock:ro"

        deploy:
            placement:
                constraints:
                    - node.role == manager
        networks:
            - playground

    jaeger:
        image: jaegertracing/all-in-one:1.46
        environment:
            - COLLECTOR_ZIPKIN_HTTP_PORT=:9411
            - COLLECTOR_OTLP_ENABLED=true
            - SPAN_STORAGE_TYPE=elasticsearch
        command:
            [
                "--es.server-urls=http://elasticsearch:9200",
                "--es.num-shards=1",
                "--es.num-replicas=0",
                "--log-level=error",
                "--span-storage.type=elasticsearch",
            ]
        ports:
            - 6831:6831/udp
            - 6832:6832/udp

            - 5778:5778
            - 16685:16685
            - 16686:16686
            - 14268:14268
            - 14269:14269
            - 14250:14250
            - 9411:9411
            - 4317:4317
            - 4318:4318
        networks:
            - playground
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.jaeger.rule=Host(`jaeger.localhost`)"
                - "traefik.http.routers.jaeger.entrypoints=web"
                - "traefik.http.services.jaeger.loadbalancer.server.port=16686"
                - "traefik.http.routers.jaeger.middlewares=myauth"
                #- "traefik.http.middlewares.myauth.basicauth.users=logs:$$2a$$12$$IJm.H6aol9cq5jTwip.spOina7czuNH2XM1qcd6jXqFptIAB2CBGO"
                - "traefik.http.middlewares.myauth.basicauth.usersfile=/run/secrets/PG_JAEGER_BASIC_AUTH"

        secrets:
            - PG_JAEGER_BASIC_AUTH

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - cluster.name=jaeger-cluster
            - discovery.type=single-node
            - http.host=0.0.0.0
            - transport.host=127.0.0.1
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
            - xpack.security.enabled=false
        volumes:
            - ./esdata:/usr/share/elasticsearch/data
        networks:
            - playground
