version: "3.9"

services:
    swarm-hello-world:
        image: lumaghg/swarm-hello-world:20231017.11
        ports:
            - 3000:4000
        environment:
            - port=4000
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
                - "traefik.http.routers.whoami.entrypoints=web"
                - "traefik.http.services.whoami.loadbalancer.server.port=4000"
            replicas: 2
            update_config:
                order: start-first
                parallelism: 0

                failure_action: rollback
                monitor: 5s

    traefik:
        image: "traefik:v2.9"
        command:
            - "--log.level=DEBUG"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--providers.docker.swarmMode=true"
            - "--entrypoints.web.address=:80"
            - "--accesslog=true"
            - "--tracing.jaeger=true"
            - "--tracing.jaeger.samplingServerURL=http://jaeger:5778/sampling"
            - "--tracing.jaeger.localAgentHostPort=jaeger:6831"
            - "--tracing.jaeger.propagation=jaeger"
            - "--api.insecure=true"
            - "--providers.docker.network=pg_default"
        ports:
            - 80:80

        volumes:
            - "//var/run/docker.sock:/var/run/docker.sock:ro"

        deploy:
            placement:
                constraints:
                    - node.role == manager

    jaeger:
        image: jaegertracing/all-in-one:1.46
        environment:
            - COLLECTOR_ZIPKIN_HTTP_PORT=:9411
            - COLLECTOR_OTLP_ENABLED=true
        ports:
            - 6831:6831/udp
            - 6832:6832/udp

            - 5778:5778
            - 16685:16685
            - 16686:16686
            - 14268:14268
            - 14269:14269
            - 14250:14250
            - 9411:9411
            - 4317:4317
            - 4318:4318
